apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  labels:
    app: customers-deployment
spec:
  selector:
    matchLabels:
      app: customers-deployment
  template:
    metadata:
      labels:
        app: customers-deployment
    spec:
      containers:
        - name: customers
          image: docker.io/bazel/customers/cmd/serve:image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: COCKROACH_HOST
              value: database-service
            - name: COCKROACH_PORT
              value: "26257"
            - name: COCKROACH_USER
              value: root
            - name: COCKROACH_DATA
              value: defaultdb
